### ISSUE TITLE
nvim-r workflow info

### ISSUE THREAD

**Issue by oddish3** [wurli/dotfiles#1]
hey, i would like to enquire on your current workflow with your nvim-r and dotfiles. i currently use nvim for latex editing and the usual IDEs for code editing. however i feel there is little documentation / resources for an nvim data science workflow / nvim config, hence i would like to know yours. 

there is some stuff of this online, but i am not overly convinced on it. i would like an editor that has lsp/ completion, vim motions and a cheatsheet/ which key setup, if this is something you'd be interested in looking at, let me know!

**Comment by wurli** [comment]
Heya,

My setup is still very much a work in progress. Particularly with R, I haven't put it through its paces on a serious project yet, so it's likely to change quite quickly as I go through it. If you're an R user though, I definitely can recommend [R.nvim](https://github.com/R-nvim/R.nvim) - my experience with it has been wholly positive so far, but you'll need to learn to read docs within Neovim to make the most of it. 

Agree with you generally though - haven't found a tonne of stuff online about using Neovim specifically for data science. I might make a video/blog post about this sooner or later if I find a setup which works really well. Regarding getting set up with Neovim itself, my personal experience is that I needed to go through quite a few resources until I found ones I felt reasonably confident were up to date. 

For setting Neovim up, I'd recommend [_typecraft_'s YouTube course](https://www.youtube.com/watch?v=zHTeCSVAFNY&list=PLsz00TDipIffreIaUNk64KxTIkQaGguqn), which is excellent and is still only a few months old.

For getting going with vim motions (if you're interested), I'd recommend the series [Vim As Your Editor](https://www.youtube.com/watch?v=X6AR2RMB5tE&list=PLm323Lc7iSW_wuxqmKx_xxNtJC_hJbQ7R) by ThePrimeagen.

Hope this is somewhat helpful!
